---
title: "run_preprocessing_task-reversalLearning"
author: "Lieke Hofmans"
date: "2023-10-04"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warnings = FALSE)

# packages
list.of.packages <- c("tidyverse", "dplyr", "ggplot2", "tidyr", "readr")
new.packages <- list.of.packages[!(list.of.packages %in% installed.packages()[,"Package"])]
if(length(new.packages)) install.packages(new.packages)

library(tidyverse)
library(dplyr)
library(ggplot2)
library(tidyr)
library(readr)

# directories
project_wd <- "P:/fMRI Projects/fMRI Project Mushroom Highschool"
setwd(project_wd)

analysis_dir <- file.path(project_wd, "analysis")
bids_dir <- file.path(project_wd, "bids")
derivatives_RL_dir <- file.path(bids_dir, "derivatives/beh/reversalLearning")

```

```{r import data, include=FALSE}

# import which participants need to be excluded
participants_to_exclude <- read.csv(file.path(analysis_dir, "participants_to_exclude.csv"))

# import Reversal Learning data
list_subjects <- list.dirs(path = bids_dir, full.names = TRUE, recursive = FALSE)
list_subjects <- list_subjects[grepl(".*sub-[2-8][0-9]{2}", list_subjects)]
df_all <- data.frame()

for (iSubject in list_subjects){
  RLfile <- list.files(path = file.path(iSubject, "beh"), pattern = "sub-.*_task-reversalLearning_beh.csv", full.names = TRUE)
  if (length(RLfile) > 0) {
    if (file.size(RLfile) > 2000){
      RLdata <- read.csv(RLfile, fileEncoding="UTF-8-BOM")
      # keep only rows with behavioral task data
      RLdata <- RLdata[!is.na(RLdata$participant),]
      # keep only columns with relevant behavioral task data
      RLdata_filtered <- RLdata %>% select(participant:position_triangle)
      df_all <- rbind(df_all, RLdata_filtered)
    }
  }
} 
RLdata <- df_all[!df_all$participant %in% participants_to_exclude$exclude_beh,]
colnames(RLdata)[1] <- "sID"

```

```{r preprocess WM data}

# define RL scores:
# i) Accuracy
# ii) Win-stay: repeat response if it was rewarded in previous trial
# iii) Lose-shift: shift response if it was punished in previous trial

RLsumm <- data.frame(matrix(ncol = 4, nrow = length(unique(RLdata$sID))))
colnames(RLsumm) <- c("sID", "RL_accuracy", "RL_winStay", "RL_loseShift")

n_row <- 1
for (iSubject in unique(RLdata$sID)){
    subject_data <- RLdata[RLdata$sID == iSubject,]
    RLsumm$sID[n_row] <- iSubject
    RLsumm$RL_accuracy[n_row] <- nrow(subject_data[subject_data$correct==1,]) / nrow(subject_data)
    RLsumm$RL_winStay[n_row] <- nrow(subject_data[subject_data$previous_outcome=="win" & subject_data$stay_shift=="stay",]) / nrow(subject_data[subject_data$previous_outcome=="win",])
    RLsumm$RL_loseShift[n_row] <- nrow(subject_data[subject_data$previous_outcome=="lose" & subject_data$stay_shift=="shift",]) / nrow(subject_data[subject_data$previous_outcome=="lose",])
    n_row <- n_row + 1
}

# histogram of RL scores
# Accuracy
ggplot(data = RLsumm, aes(x = RL_accuracy)) +
  geom_histogram(binwidth = 0.05, color = "black", fill = "grey") + 
  theme_classic(base_size = 16) +
  geom_vline(aes(xintercept = mean(RL_accuracy)), size = 1, color = "red") +
  xlim(0,1) + 
  xlab("RL accuracy")

# Win-stay
ggplot(data = RLsumm, aes(x = RL_winStay)) +
  geom_histogram(binwidth = 0.05, color = "black", fill = "grey") + 
  theme_classic(base_size = 16) +
  geom_vline(aes(xintercept = mean(RL_winStay)), size = 1, color = "red") +
  xlim(0,1) + 
  xlab("RL win-stay rate")

# Lose-shift
ggplot(data = RLsumm, aes(x = RL_loseShift)) +
  geom_histogram(binwidth = 0.05, color = "black", fill = "grey") + 
  theme_classic(base_size = 16) +
  geom_vline(aes(xintercept = mean(RL_loseShift)), size = 1, color = "red") +
  xlim(0,1) + 
  xlab("RL lose-shift rate")

```



```{r save data}
# save data
if (!isTRUE(file.info(derivatives_RL_dir)$isdir)) dir.create(derivatives_RL_dir, recursive = TRUE)
write_csv(RLdata, file.path(derivatives_RL_dir, "group_task-reversalLearning_preproc-trialwise.csv"))
write_csv(RLsumm, file.path(derivatives_RL_dir, "group_task-reversalLearning_preproc-participantwise.csv"))


`````